from enum import Enum


class TemplateDataFieldV1GoogleFieldSettingsGoogleFieldType(str, Enum):
    ACCOUNT_NAME = "ACCOUNT_NAME"
    EVENT_CONFIRMATION_CODE = "EVENT_CONFIRMATION_CODE"
    EVENT_DOORS_OPEN = "EVENT_DOORS_OPEN"
    EVENT_END = "EVENT_END"
    EVENT_GATE = "EVENT_GATE"
    EVENT_ROW = "EVENT_ROW"
    EVENT_SEAT = "EVENT_SEAT"
    EVENT_SECTION = "EVENT_SECTION"
    EVENT_START = "EVENT_START"
    EVENT_TICKET_MONEY = "EVENT_TICKET_MONEY"
    EVENT_TICKET_TYPE = "EVENT_TICKET_TYPE"
    EVENT_VENUE = "EVENT_VENUE"
    LOYALTY_POINTS = "LOYALTY_POINTS"
    MESSAGES = "MESSAGES"
    NOT_USED = "NOT_USED"
    OFFER_DETAILS = "OFFER_DETAILS"
    OFFER_FINEPRINT = "OFFER_FINEPRINT"
    TEXT_MODULE_DATA = "TEXT_MODULE_DATA"

    def __str__(self) -> str:
        return str(self.value)
