from enum import Enum


class TemplateDataFieldV1SamsungFieldSettingsSamsungFieldType(str, Enum):
    CUSTOMER_SERVICE_INFO = "CUSTOMER_SERVICE_INFO"
    END_DATE = "END_DATE"
    EVENT_ENTRANCE = "EVENT_ENTRANCE"
    EVENT_GRADE = "EVENT_GRADE"
    EVENT_ISSUE_DATE = "EVENT_ISSUE_DATE"
    EVENT_RESERVATION_NUMBER = "EVENT_RESERVATION_NUMBER"
    EVENT_SEAT_CLASS = "EVENT_SEAT_CLASS"
    EVENT_SEAT_LAYOUT_IMAGE = "EVENT_SEAT_LAYOUT_IMAGE"
    EVENT_SEAT_NUMBER = "EVENT_SEAT_NUMBER"
    NOTICE_DESCRIPTION = "NOTICE_DESCRIPTION"
    NOT_USED = "NOT_USED"
    START_DATE = "START_DATE"
    USER = "USER"

    def __str__(self) -> str:
        return str(self.value)
